### ISSUE TITLE
FR: frontmatter complement of tags should be case insensitive

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#115]
Annoyingly, I can never remember whether I use a tag lowercased or capitalized – Obsidian does not make a difference, and for all intents and purposes, Obsidian ignores casing when it comes to tags, e.g. merging "acb" and "Abc" into one tag in the tag pane.

However, this has the side effect, that various complements often suggests both casings for a tag for me, which fills up the suggester, while the choice actually makes no difference to Obsidian.

So I suggester that for the tag-field of the frontmatter, only one tag should be shown when multiple tags only differ by spelling. A pragmatic solution could be to simply lowercase all tags?

<img width="471" alt="Pasted Image 2022-04-18 10 57 42" src="https://user-images.githubusercontent.com/73286100/163784900-ed053890-29bc-4b5b-a8b8-08d66a779f2d.png">

**Comment by tadashi-aikawa** [comment]
> A pragmatic solution could be to simply lowercase all tags?

I examined the behavior of tag completion and found that it seems to prioritize the first tag that appears. I'll implement it so 👍

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v6.1.0-beta5](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.1.0-beta5) 🚀

**Comment by chrisgrieser** [comment]
both tags still appear for me? 🤔 
<img width="416" alt="Pasted image  2022-05-04 11 19 03" src="https://user-images.githubusercontent.com/73286100/166654439-3dde4ea2-6a01-408c-8050-5aa2f1aa9c35.png">

**Comment by tadashi-aikawa** [comment]
Does it reproduce after rebooting Obsidian, too?

**Comment by chrisgrieser** [comment]
yes

**Comment by tadashi-aikawa** [comment]
I couldn't reproduce it. 🤔 

![image](https://user-images.githubusercontent.com/9500018/166661847-2864f4ed-7be8-4607-a4f3-f8dc2fcde437.png)

Is your plugin version v6.1.0-beta5 certainly?

**Comment by chrisgrieser** [comment]
yes, I am!
<img width="1108" alt="Pasted image  2022-05-04 12 18 32" src="https://user-images.githubusercontent.com/73286100/166663566-496baa92-0587-47e6-986b-6170a64f67bc.png">

**Comment by tadashi-aikawa** [comment]
Could you tell me your settings by [this command](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AECopy%20plugin%20settings/)?

```
{
    "version": "6.0.0",
    "mobile": false,
    "settings": {
        "strategy": "japanese",
        "matchStrategy": "prefix",
        "maxNumberOfSuggestions": 20,
        "maxNumberOfWordsAsPhrase": 3,
        "minNumberOfCharactersTriggered": 0,
        "minNumberOfWordsTriggeredPhrase": 1,
        "complementAutomatically": true,
        "delayMilliSeconds": 0,
        "disableSuggestionsDuringImeOn": false,
        "insertAfterCompletion": false,
        "firstCharactersDisableSuggestions": ":/^",
        "showMatchStrategy": true,
        "showIndexingStatus": true,
        "descriptionOnSuggestion": "Short",
        "selectSuggestionKeys": "Enter",
        "additionalCycleThroughSuggestionsKeys": "None",
        "openSourceFileKey": "None",
        "propagateEsc": true,
        "enableCurrentFileComplement": false,
        "onlyComplementEnglishOnCurrentFileComplement": false,
        "enableCurrentVaultComplement": false,
        "includeCurrentVaultPathPrefixPatterns": "",
        "excludeCurrentVaultPathPrefixPatterns": "",
        "includeCurrentVaultOnlyFilesUnderCurrentDirectory": false,
        "enableCustomDictionaryComplement": true,
        "customDictionaryPaths": "_Privates/dict.md\n_Privates/dict.json",
        "columnDelimiter": "Comma",
        "customDictionaryWordRegexPattern": "",
        "delimiterToHideSuggestion": ";;;",
        "delimiterToDivideSuggestionsForDisplayFromInsertion": " >>> ",
        "caretLocationSymbolAfterComplement": "<CARET>",
        "displayedTextSuffix": " => ...",
        "enableInternalLinkComplement": true,
        "suggestInternalLinkWithAlias": false,
        "excludeInternalLinkPathPrefixPatterns": "",
        "enableFrontMatterComplement": true,
        "frontMatterComplementMatchStrategy": "inherit",
        "insertCommaAfterFrontMatterCompletion": false,
        "showLogAboutPerformanceInConsole": true,
        "selectionHistoryTree": null,
        "loadSpellcheckWords": false
    }
}
```

**Comment by chrisgrieser** [comment]
sure, here:

```json
{
    "version": "6.1.0-beta5",
    "mobile": false,
    "settings": {
        "strategy": "default",
        "matchStrategy": "prefix",
        "maxNumberOfSuggestions": 30,
        "maxNumberOfWordsAsPhrase": 3,
        "minNumberOfCharactersTriggered": 4,
        "minNumberOfWordsTriggeredPhrase": 1,
        "complementAutomatically": true,
        "delayMilliSeconds": 450,
        "disableSuggestionsDuringImeOn": false,
        "insertAfterCompletion": false,
        "firstCharactersDisableSuggestions": ":/^",
        "showMatchStrategy": false,
        "showIndexingStatus": false,
        "descriptionOnSuggestion": "Short",
        "selectSuggestionKeys": "Enter",
        "additionalCycleThroughSuggestionsKeys": "Ctrl/Cmd+J, Ctrl/Cmd+K",
        "openSourceFileKey": "Ctrl/Cmd+Enter",
        "propagateEsc": false,
        "enableCurrentFileComplement": false,
        "onlyComplementEnglishOnCurrentFileComplement": true,
        "enableCurrentVaultComplement": false,
        "includeCurrentVaultPathPrefixPatterns": "Writing/",
        "excludeCurrentVaultPathPrefixPatterns": "",
        "includeCurrentVaultOnlyFilesUnderCurrentDirectory": true,
        "enableCustomDictionaryComplement": true,
        "customDictionaryPaths": "Meta/Autocomplete Dictionaries/+ Tech Vocabulary.md\nMeta/Autocomplete Dictionaries/+ citekey-autocomplete.txt\nMeta/Autocomplete Dictionaries/+ English.md\nMeta/Autocomplete Dictionaries/+ German.md\nMeta/Autocomplete Dictionaries/+ Snippets.md\nMeta/Autocomplete Dictionaries/+ Sociology – English.md\nMeta/Autocomplete Dictionaries/+ Sociology – German.md",
        "columnDelimiter": "Pipe",
        "customDictionaryWordRegexPattern": "",
        "delimiterToHideSuggestion": "",
        "delimiterToDivideSuggestionsForDisplayFromInsertion": ">>>",
        "caretLocationSymbolAfterComplement": "§§",
        "displayedTextSuffix": " +",
        "enableInternalLinkComplement": false,
        "suggestInternalLinkWithAlias": false,
        "excludeInternalLinkPathPrefixPatterns": "PhD Thesis/\nLiterature Notes/\nWriting/\nProjekte/\nMeta/",
        "enableFrontMatterComplement": true,
        "frontMatterComplementMatchStrategy": "prefix",
        "insertCommaAfterFrontMatterCompletion": true,
        "showLogAboutPerformanceInConsole": false,
        "selectionHistoryTree": null,
        "loadSpellcheckWords": false,
        "overwriteDuplicatedExistedPhrase": true,
        "ignoreEnterKey": false,
        "ignoreTabKey": false,
        "onlySuggestFromCustomDictionaries": false
    }
}
```

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Thanks! And sorry, I found super easy mistaken... I will fix it 👍

**Comment by chrisgrieser** [comment]
Thank you, now it works! 🥳 

that the value is the same as in tag completion doesn't matter too much, since Obsidian ignores the casing of tags anyway.

**Comment by tadashi-aikawa** [comment]
Released [v6.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.1.0) 🚀
