### ISSUE TITLE
Layout broken in Obsidian v0.15.4

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-various-complements-plugin#148]
![image](https://user-images.githubusercontent.com/9500018/177378881-b2cdfdf9-0485-4a60-baff-7f67c16de705.png)

**Comment by ryadaj** [comment]
i am also having this issue

<img width="343" alt="CleanShot 2022-07-05 at 16 39 03@2x" src="https://user-images.githubusercontent.com/82765301/177412485-5ba7b501-c79c-45ee-95f0-aef93328e7b9.png">

<img width="620" alt="CleanShot 2022-07-05 at 16 38 43@2x" src="https://user-images.githubusercontent.com/82765301/177412498-be616e33-6b8a-4b2c-a305-15c3792d444e.png">

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.2) 🚀

**Comment by tyf2018** [comment]
After updating to 7.0.2, the problem is not resolved, the text is still right aligned, the effect I want is: left aligned as before.

**Comment by tadashi-aikawa** [comment]
I couldn't reproduce it in Sandbox vault 🤔 

![image](https://user-images.githubusercontent.com/9500018/177451649-6dd1e00d-856c-4259-98fb-c94714c47b30.png)

**Comment by tadashi-aikawa** [comment]
FYI: @ryadaj 

Broking layout about tag completion seems to be a bug about Obsidian v0.15.4 because it occurs in the Sandbox vault where it is not installed Various Complements.

![](https://user-images.githubusercontent.com/82765301/177412485-5ba7b501-c79c-45ee-95f0-aef93328e7b9.png)

**Comment by ryadaj** [comment]
hello friend! i attach a gif for you showing that there is also an issue with aliases

hopefully next insider release will fix

![CleanShot 2022-07-06 at 17 08 12](https://user-images.githubusercontent.com/82765301/177643577-dab9241c-6bfd-40ad-9af5-9396bc01fbe5.gif)

**Comment by tadashi-aikawa** [comment]
Thanks @ryadaj :)

Fixed in [v7.0.3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.3) 🚀

**Comment by tyf2018** [comment]
> After updating to 7.0.2, the problem is not resolved, the text is still right aligned, the effect I want is: left aligned as before.

After updating to 7.0.3 my problem was solved, thanks!

**Comment by ryadaj** [comment]
Thank you!! I am still having the issue with tags, but the aliases issue is fixed

<img width="431" alt="Screen Shot 2022-07-07 at 08 07 29" src="https://user-images.githubusercontent.com/82765301/177769542-37607d21-d287-4561-be6f-546011c40b05.png">

**Comment by tadashi-aikawa** [comment]
@ryadaj 
Please read it :)

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/148#issuecomment-1175730874

**Comment by ryadaj** [comment]
Ah yes, ok! Thank you :)

**Comment by tadashi-aikawa** [comment]
FYI: I could fix the problem by using the following CSS.

```
.suggestion-container > .suggestion > .suggestion-item {
  align-items: inherit;
  justify-content: inherit;
}
```
