### ISSUE TITLE
conflict with slash command

### ISSUE THREAD

**Issue by lifesign** [tadashi-aikawa/obsidian-various-complements-plugin#49]
it seems obsidian core plugin "Slash commands" was broken when various complements plugin was enabled. conflicted?

**Comment by tadashi-aikawa** [comment]
@lifesign 
What version do you use?

**Comment by tadashi-aikawa** [comment]
I could reproduce it 👍

**Comment by tadashi-aikawa** [comment]
@lifesign 
I have released to [v3.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.0) 🚀

Please confirm whether it works as you expected.

**Comment by lifesign** [comment]
seems ok, thx~

**Comment by keithadams** [comment]
I'm having this problem still. Using a fresh vault with slash commands enabled and Various Complements installed.

Create a note titled 'Internal Link'. Then type `/int` for the **Add Internal Link** command.

1. Typing `/in` will show Slash commands
2. Typing `/int` will show only VC

**Versions:**
- Obsidian 0.13.19
- VC 4.2.0

**Comment by tadashi-aikawa** [comment]
@keithadams

Thanks. I could reproduce it.

But, strangely, it occurs only in a new vault. I couldn't reproduce it in my main vault... 🤔

**Comment by keithadams** [comment]
@tadashi-aikawa 

Interesting, I was having the problem on my main vault as well.

I installed the beta and it's fixed. Thank you very much!

**Comment by tadashi-aikawa** [comment]
Thank you for your confirmation!

I will close this issue after release v5.0.0.

**Comment by tadashi-aikawa** [comment]
I have released to [v5.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.0.0) 🚀

So closed this issue.
