### ISSUE TITLE
[Feature Request]  Add Ignore Enter key and Ignore Tab key options

### ISSUE THREAD

**Issue by dummifiedme** [tadashi-aikawa/obsidian-various-complements-plugin#59]
Currently, if we have to select a suggestion, we have to press `Enter`. It is fine on the normal use, but if the word is at the end of a sentence, while typing we press `Enter` to go to the new line, it actually selects the suggestion (which sometimes are really long phrases from the note titles :D). Therefore, it tend to get restricting to the flow of writing.

If there was an option to assign `Tab` key to select the input, then would really be great for the flow as well as typing. 
I would like it to be optional with a toggle sine many people might be using `Tab` to shuffle between the suggestions. 

If needed, we can discuss about it. I hope I clarified the suggestion :smile:

**Comment by tadashi-aikawa** [comment]
Hi, @dummifiedme. Thank you for your suggestion :)

I already implemented this feature at https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/19. So I think you can select a suggestion by `Tab`.

Could you confirm it?

**Comment by dummifiedme** [comment]
> Could you confirm it?

My bad, yes it works. 
I don't know why it didn't when I had tried earlier. And since then I was using `Enter`, haha.

Sorry! and Thanks! :)

**Comment by tadashi-aikawa** [comment]
@dummifiedme 
Good!

If you want to avoid selecting the suggestion unintentionally, I may implement the feature to ignore the Enter key (Go to the new line and close suggestions). 🤔

**Comment by dummifiedme** [comment]
Oh, yes.
I totally forget that part :D
I would love an option to turn Enter off completely. :)

**Comment by tadashi-aikawa** [comment]
O.K 👍  Could you reopen this issue and rename its title?

**Comment by tadashi-aikawa** [comment]
Thanks!

I had already implemented this issue. So it will be released at v4.0.0.

**Comment by tadashi-aikawa** [comment]
@dummifiedme 
I have released to [v4.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/4.0.0) 🚀

Please confirm whether it works as you expected.

**Comment by dummifiedme** [comment]
Yes, it does!
Thanks!

**Comment by urnotjl** [comment]
Hi Tadashi or anyone who knows the answer,

I am still experiencing issues with selecting words using the 'Tab' key. It goes straight to tabbing the entire line, which seems to conflict with the built-in use of 'Tab'. However, if I change the option to 'Enter', the selection works well and is not recognized by Obsidian as an 'Enter' use.

And i chekced out V4 release and current option, can't see any image of those options ? 

Thanks in advance !! 

> @dummifiedme I have released to [v4.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/4.0.0) 🚀
> 
> Please confirm whether it works as you expected.

**Comment by urnotjl** [comment]
Pfff, the problem has been solved by reinstalling... Forget about this golden rule😢 

thanks your work ,Tadashi
